/**
 * A Maven report plugin that creates reports based on software design quality metrics generated by
 * <a href="https://github.com/clarkware/jdepend">JDepend</a>.
 *
 * @author RealLifeDeveloper
 */
package com.reallifedeveloper.maven.jdepend;
